version: '2.1'

networks:
  transport:
    driver: macvlan
    driver_opts:
      parent: tap0
    ipam:
      config:
        - subnet: 192.168.50.0/24
          gateway: 192.168.50.253

services:
  dummyran:
    container_name: dummyenb
    build: ./
    ipc: shareable
    cap_add:
      - SYS_NICE
    networks:
      transport:
        ipv4_address: 192.168.50.149
    command:
      - srsenb
      - /config/enb.conf.fauxrf
      - --enb.name=dummyENB01
      - --enb.mcc=722
      - --enb.mnc=07
      - --enb.enb_id=18AF1
      - --enb.tac=0x0001
      - --enb.cell_id=01
      - --enb.mme_addr=192.168.50.101
      - --enb.gtp_bind_addr=192.168.50.149
      - --enb.s1c_bind_addr=192.168.50.149
      - --enb_files.rr_config=/config/rr.conf
      - --enb_files.sib_config=/config/sib.conf
      - --enb_files.drb_config=/config/drb.conf
  dummyclient:
    container_name: dummyue
    build: ./
    ipc: "container:dummyenb"
    cap_add:
      - NET_ADMIN
      - SYS_NICE
    devices:
      - /dev/net/tun
    network_mode: "none"
    depends_on:
      - dummyran
    command:
      - srsue
      - /config/ue.conf.fauxrf
      - --usim.imsi=722070000000008
      - --usim.k=c8eba87c1074edd06885cb0486718341
      - --usim.algo=milenage
      - --usim.opc=17b6c0157895bcaa1efc1cef55033f5f
      - --nas.apn=internet
